language: python
python:
  - "3.6"
install: true
services:
  - docker
before_install:
  - docker build -t wdwnt/fastpass:latest .
script:
  - bash docker_push.sh
env:
  global:
  - secure: Mi6bd2HD/y+09CU8/vqU1AFMg1UW3AWylKef6zgL6udRGX1u8r/RkXsWyBlrZu3y4Lz7Gl2r1Zp+0ojRJkU9yI8JsSYTE5LaAJJxqe9UyEAKhGUUbJdDogE+X5s+4v11C6x2blF3SVeOfRyzDC5vZlfFSH0U1jeVrOBZP1XlBatyyBiXX/PDl/PRuE9PFKrhOUj49FUUiAfNsOo89tah6CZV2kYL4wyMDjm/jS28WyKLLy0C+tbtyAeLtrG6f7p2uFUxkpfBfB9KLKNPxzPjhd201tI6kUeh5liz71D6j2NAwHcCe3MESZ+3JyybrfFP/qx2VW3ZTuX4w4CKU01H+gAMVg11cnX6dUowefNYZREaA2Em1u1nKdF8XnugHNGXAAKDRy8vzMH3Nxbwn9vPV9w9r+MxpKpJHrbZflHD17vOhDdfJR5ze0zaPJMnLRHSFp4G3WT6usYHq6jhIL3KaLs+uCor3PtURFpGgEw3JNwE8aJnQQKls15R7nr8myxQymUBiVtiOGUyyy2FD2Eq8HiaTb3v1TI+IrOoLmN3wp8tG9Mza9lDKdIiWjW9tZT1/SyjUFHNBxrEsW1DYjEhqz987SRP4//obQGos9zAP1uYF9T85iufqpLsuUwWSmPYuL5JDWIvsL1d3zXT5v8FohinG33gyoyNLbjzZeB9KKE=
  - secure: svTk/ZQQn8Ux4Bg94lSThzHXNQ94KTLhzgW5+cDN27fBAp6Cr4gENhGDgw3AlaE9SW946VL67Xr7sNkNcTi6y7XKOZGPzBm61K6I4t3CqO78fc3hfCJBo2/xLv+DvuME9F+HVuAsrHXcb4IK5S1M5PI2I8p+s1M8LXFFJb/wACNzCqBgkDG2GglTBAfjtBtzAuPhQtESOYX012WVz9Wu7euZhCR9PhC50QBNOSuUOjDAeK6YM5l8QdWF0RHzl2DvHChMkrLxjgVxndreUPMsE32KaaBu60u/e3ztlqDKFuBdmGGKzu8Hv+zbT1G1VPFhuwyMmI1GvP/brRpWzRZuSdoQZluYmbE0Oe05tgoydoQxs4cKApCzL3b5iWPy57b89l03Tbil/CknABYpL9DxXxWc1xzyffdH1v/UNyZJ1xWfbS48GnI+eRBjsxKCt1hOtNfDRma/Wy2dxNlyrfvN4s+U1VgJuk/iNptdI6ZS3bzoAiiFi9OcF7wKfLPZhfTmjGD4s3tmOpRC1PAoTZWgFFPu2T+HWxUiKLNqOPnNFgV6ROkBreqd0d7J7oLQOJNO8bCuUxZ2fQ0X2MNBh9VcGQPKH2W3Mok27xFz9DjfBBTAM8HLOCM2L5et+BTkz3a8ivOQBx12svJK9PP52SzUA1CSja70Sk62hKUvii6eE2g=
